### ISSUE TITLE
Research on security

### ISSUE THREAD

**Issue by mjenrungrot** [cs121-team-panda/coconut-interpreter-flask#35]
Major security concerns for online compilers/interpreters are malicious codes submitted from users. In the current system, the code is evaluated on the server-side. From the server perspective, the server may happen to run the potentially malicious code. Some potential problems may arise, at least but not limited to:
- DDoS attack to exhaust the server's resources.
- Manipulate file structures using `os` module

There are two main ways of addressing this security concern: running code on client-side and on server-side. 

1. **Client-side**
In short, we can execute everything client-side using JavaScript, and possibly use tools like [Brython](https://brython.info/) that essentially converts Python script to JavaScript and in order for it to be executed on the client-side.

Keypoints
- Not work with some of the libraries.
- Depend on specific versions of library.
- Tend to be 3 to 5 times slower.

2. **Server-side**
2.1 Use _Sandbox_
General ideas are to use the concept of sandboxing that lets the potentially malicious code in that sandbox. See more discussion [here](https://stackoverflow.com/questions/4249063/run-an-untrusted-c-program-in-a-sandbox-in-linux-that-prevents-it-from-opening-f/4249228#4249228). In Python, we have some discussions [here](https://wiki.python.org/moin/Asking%20for%20Help/How%20can%20I%20run%20an%20untrusted%20Python%20script%20safely%20%28i.e.%20Sandbox%29).
2.2 Use _RestrictedPython_
[RestrictedPython 4.0b2](https://pypi.python.org/pypi/RestrictedPython/) is a defined subset of the Python language which allows to provide a program input into a trusted environment.

Keypoints
- Faster
- Not depend on specific versions of library.

Thoughts on this issue are very appreciated.

**Comment by mjenrungrot** [comment]
http://doc.pypy.org/en/latest/sandbox.html

**Comment by jcruz** [comment]
- [Running untrusted python code](https://security.stackexchange.com/questions/77209/running-untrusted-python-code)
- [Safely executing arbitrary code](https://softwareengineering.stackexchange.com/questions/351132/safely-executing-arbitrary-code)
- [Best practices for execution of untrusted code](https://softwareengineering.stackexchange.com/questions/191623/best-practices-for-execution-of-untrusted-code)

**Comment by jcruz** [comment]
https://docs.docker.com/engine/security/security/

**Comment by jcruz** [comment]
We are prioritizing performance, so closing this for now.
