### ISSUE TITLE
Make the interpreter easily embeddable within a larger HTML document

### ISSUE THREAD

**Issue by nkadonaga** [cs121-team-panda/coconut-interpreter-flask#36]
"ideally with some pre-defined starting code"

and send to the group doing the tutorial once we're done

Status: Yellow

Plans:
- [x] Get the emails of the tutorial team.
- [x] Communicate with other teams, ask for their pipeline.
- [x] Show how to embed the editor to the other team.

**Comment by jcruz** [comment]
Still needs optimizations

**Comment by jcruz** [comment]
Issue is resolved. Opened https://github.com/cs121-team-panda/coconut-interpreter-react/issues/4 as enhancement feature.
