### ISSUE TITLE
Allow compilation parameters

### ISSUE THREAD

**Issue by nkadonaga** [cs121-team-panda/coconut-interpreter-flask#37]
'provide a way to change the compilation parameters (e.g. compile to Python 3 instead of universal Python as if you had passed "--target 3")'

Plans: 
- [x] write/test backend 
- [ ] implement frontend (@jcruz)
  - ideas: a gear? hover over run button for options?
- [x] merge backend PR #51

**Comment by nkadonaga** [comment]
assigned @jcruz since I don't think I would be able to figure out how/where to stick in a form field for the compile parameters

**Comment by mjenrungrot** [comment]
Postponed to later phase based on the discussion that it may be too advanced for end users.

**Comment by jcruz** [comment]
Will revisit later if needed.

**Comment by jcruz** [comment]
Remaining work on the frontend
- https://github.com/cs121-team-panda/coconut-interpreter-react/issues/6
- https://github.com/cs121-team-panda/coconut-interpreter-react/issues/7
