### ISSUE TITLE
Coconut-specific syntax highlighting

### ISSUE THREAD

**Issue by nkadonaga** [cs121-team-panda/coconut-interpreter-flask#39]
'nicely highlight Coconut-specific syntax (e.g. "match" or "case")'

Status: GREEN

Plans:
- [x] List all the keywords to be highlighted (Ref [here](https://github.com/evhub/coconut/blob/master/coconut/constants.py#L351))
- [x] Separate keywords into different groups because we plan to highlight them differently, I think.
- [x] Extend the syntax formatting based on [here](https://github.com/ajaxorg/ace/wiki/Creating-or-Extending-an-Edit-Mode) on some small expressions + Test
- [x] Populate and extend the syntax highlighting for all keywords.

**Comment by nkadonaga** [comment]
Don't hesitate if you want to do this instead 👀

**Comment by brittanywang** [comment]
Okay so I was able to get the builtins, keywords, magic methods, and a few specific ones that were highlighted on the documentation but not included in the list. I'm sorta confused on where to include the operators on coconut.js and how to classify MatchError and StopIteration...

**Comment by mjenrungrot** [comment]
@brittanywang Can you give some examples?

**Comment by brittanywang** [comment]
@mjenrungrot Examples of the newly incorporated syntax? Quick update though, Jon created a regex for keyword.operator so now I'm just putting the new_operators in that.

**Comment by mjenrungrot** [comment]
@brittanywang Yes. Can I also get an update on whether how many syntaxes we have covered?

**Comment by mjenrungrot** [comment]
Can you also generate the new github page?

**Comment by nkadonaga** [comment]
Is that just
`yarn build`
`gh-pages -d build`
on my local repo?

**Comment by jcruz** [comment]
Done.

@nkadonaga  `yarn deploy` is the command for that, but you need https://github.com/cs121-team-panda/coconut-interpreter as the origin remote for it to work.

**Comment by nkadonaga** [comment]
@jcruz 😍😍😍 Thanks, that explains it!
