### ISSUE TITLE
Highlight tracebacks in red

### ISSUE THREAD

**Issue by nkadonaga** [cs121-team-panda/coconut-interpreter-flask#40]
Status: GREEN

Task:
- [ ] Let's highlight all errors in red.

Plans:
- [x] Parse traceback in backend and send object with line number, error message to client

**Comment by jcruz** [comment]
Screenshots:

Coconut
<img width="1091" alt="screen shot 2018-03-11 at 2 19 45 pm" src="https://user-images.githubusercontent.com/8571671/37258606-7e91705c-2537-11e8-8e4b-9e34ee289433.png">
<img width="1091" alt="screen shot 2018-03-11 at 2 20 04 pm" src="https://user-images.githubusercontent.com/8571671/37258611-828efa8a-2537-11e8-822d-5c59431764a7.png">

Python
<img width="1091" alt="screen shot 2018-03-11 at 2 20 16 pm" src="https://user-images.githubusercontent.com/8571671/37258612-8628b3e8-2537-11e8-9ad7-ae460f0a2056.png">
<img width="1091" alt="screen shot 2018-03-11 at 2 20 20 pm" src="https://user-images.githubusercontent.com/8571671/37258615-89d1ee56-2537-11e8-96c9-f5019a8414dc.png">
