### ISSUE TITLE
write unit tests for the prototype frontend

### ISSUE THREAD

**Issue by nkadonaga** [cs121-team-panda/coconut-interpreter-flask#5]

**Comment by jcruz** [comment]
Resolved in https://github.com/cs121-team-panda/coconut-interpreter-react/commit/cd432547f6527788218ae7e091366b76f0e9bca6 & https://github.com/cs121-team-panda/coconut-interpreter-react/commit/58e44dcc1f12b71a492d36a841254ba55014427f
