### ISSUE TITLE
Measure run-time for each components.

### ISSUE THREAD

**Issue by mjenrungrot** [cs121-team-panda/coconut-interpreter-flask#56]
Needed for Phase 2 presentations.

Progress: Green

Plans: 
- [x] Measure the run-time for all coconut code from the tutorial website and put it in the table.
- [x] Measure the run-time on Heroku; try with small code and big code from the tutorial. 
- [x] Measure the run-time on AWS; same as above.

**Comment by mjenrungrot** [comment]
Can you create a markdown for the performance of our system? Probably, put things in this format:

| Code      | Compiler Time (mean + stdev) | Local Host Time (mean + stdev) | Heroku Host Time (mean + stdev) | Link To Code |
|-----------|------------------------------|--------------------------------|---------------------------------|--------------|
| Quicksort |                              |                                |                                 |              |
| ...       |                              |                                |                                 |              |
|           |                              |                                |                                 |              |

**Comment by brittanywang** [comment]
@mjenrungrot Yeah I'll get to that today!

**Comment by brittanywang** [comment]
| Code      | Compiler Time (mean + stdev) | Local Host Time (mean + stdev) | Heroku Host Time (mean + stdev) | Link To Code |
|-----------|------------------------------|--------------------------------|---------------------------------|--------------|
| Hello World |                              |                                |                                 |              |
| Factorial (Imperative)      |                              |                                |4.87/0.565125355                                 |http://coconut.readthedocs.io/en/latest/HELP.html#imperative-method              |
| Factorial (Recursive)          |                              |                                |7.105714286/1.928642503                                 |http://coconut.readthedocs.io/en/latest/HELP.html#recursive-method              |
| Factorial (Iterative)           |                              |                                |7.355714286/1.324674264                                 |http://coconut.readthedocs.io/en/latest/HELP.html#iterative-method              |
| addpattern Method 1           |                              |                                |8.691428571/1.711796606                                 |http://coconut.readthedocs.io/en/latest/HELP.html#addpattern-method              |
| addpattern Method 2           |                              |                                |9.81/2.251806682                                |http://coconut.readthedocs.io/en/latest/HELP.html#addpattern-method              |
|Quicksort (Sequence)           |                              |                                |9.801428571/1.517118195                                 |http://coconut.readthedocs.io/en/latest/HELP.html#sorting-a-sequence              |
|Quicksort (Iterator)           |                              |                                |9.134285714/0.903269195                                 |http://coconut.readthedocs.io/en/latest/HELP.html#sorting-an-iterator              |
|Vector (Constructor)           |                              |                                |7.737142857/0.590697731                                 |http://coconut.readthedocs.io/en/latest/HELP.html#n-vector-constructor              |
|2Vector           |                              |                                |8.515714286/1.124156827                                 |http://coconut.readthedocs.io/en/latest/HELP.html#vector              |
|Vector(Methods)           |                              |                                |7.737142857/0.590697731                                 |http://coconut.readthedocs.io/en/latest/HELP.html#n-vector-methods              |
|Application(Immutable N Vector)           |                              |                                |12.75/1.533307971                                 |http://coconut.readthedocs.io/en/latest/HELP.html#applications              |

**Comment by brittanywang** [comment]
This is what i have for the Heroku Host Time and links. I have the excel sheet for the data, let me know how many digits you want me to round to/keep etc. Also, do you want me to create a folder for the excel and markup file or do you just want me to upload the files?

**Comment by jcruz** [comment]
@brittanywang On localhost when you run `coconut` can you use the `-f` flag? This forces compilation instead of using the cached file, giving more accurate times.

**Comment by brittanywang** [comment]
- [] Measure the run-time on AWS Lambda

**Comment by mjenrungrot** [comment]
@brittanywang  Can you also add the results to the poster?
