### ISSUE TITLE
Improve Security

### ISSUE THREAD

**Issue by mjenrungrot** [cs121-team-panda/coconut-interpreter-flask#57]
Status: Yellow

Plans:
- [x] Get AWS Credit.
- [ ] Change CircleCI to deploy to AWS instead of Heroku.
- [x] Research AWS Lambda
- [ ] ~~(If using Docker)~~
  - [ ] ~~Setup docker image.~~
  - [ ] ~~Have a single user's requests direct to the same container and have a different container for each user.~~

References:
- https://github.com/christophetd/docker-python-sandbox
  - We would need to modify this so that each request does not create/destroy its own container.
- http://containertutorials.com/docker-compose/flask-simple-app.html
- https://djangostars.com/blog/what-is-docker-and-how-to-use-it-with-python/

**Comment by nkadonaga** [comment]
AWS Lambda Research
- How to deploy a Flask app on AWS Lambda
  - http://blog.apcelent.com/deploy-flask-aws-lambda.html
