### ISSUE TITLE
Get AWS credit

### ISSUE THREAD

**Issue by evhub** [cs121-team-panda/coconut-interpreter-flask#59]
The easiest way to get AWS credit is through HMC, since Mudd is part of the AWS educate program. [Here are the instructions for setting that up](https://docs.google.com/document/d/1Bi6YCOnCLZh92qV-gUl8NhelP7zYcjDRWJrqVuT-4nc). If that doesn't work for some reason, let me know, and I'm still trying to figure this out, but I'll probably have you file an expense report on [Coconut's Open Collective page](https://opencollective.com/coconut).

**Comment by jcruz** [comment]
Thanks Evan! We have received credit through HMC.
