### ISSUE TITLE
Collect user testing feedback

### ISSUE THREAD

**Issue by nkadonaga** [cs121-team-panda/coconut-interpreter-flask#79]
A catch-all place for feedback collected during a user testing session, which can later be broken into separate issues.

# Bugs

### ~~Minify breaks when trying to view Python (known bug)~~ REMOVED
* Reviewer: Prof. Kate, James R., Yucheng W.
  * Steps to reproduce the problem: Use minify and then click Python checkbox, output breaks (known bug)

### ~~Python 2 doesn't work (known bug)~~ FIXED
* Reviewer: Collin V., Jamie K.
  * Steps to reproduce the problem: Select different target under compilation parameters

# Suggestions

## App

* Reviewer: Prof. Kate
  * Help the tutorial team to be able to add a "run" button next to a block of code so that the output will appear directly under it. 
    * Talk to tutorial team for API functions
  * ~~Information icon/pop-up to tell first-time users what the options mean~~ RESOLVED
  * ~~Add label for "Coconut Compilation Parameters"~~ RESOLVED
  * ~~Show line numbers in the editor and compiled Python (add an option?)~~ RESOLVED
  * ~~Include a way to save the file~~ RESOLVED
  * Stress-testing? (What happens when we have a timeout?) 
    * Timeout error is not informative

* Reviewer: Collin V., Jamie K.
  * ~~Explain what `no_tco` is~~ REMOVED

* Reviewer: James R., Yucheng W.
  * ~~What is the difference between "Keep line numbers" and "Keep lines"?~~ REMOVED
  * ~~(repeat) Explain what `no_tco` is~~
  * ~~(repeat) Show line numbers in the editor and compiled Python~~
  * ~~Different font size~~  RESOLVED

* Reviewer: Chen P., Nelll W.
  * Theme color options (e.g. purple)
  * ~~(repeat) Bigger font size~~
  * ~~(repeat) Show line numbers in the editor and compiled Python~~

* Reviewer: Evan H.
  * ~~Can't tell difference between traceback and not traceback~~ RESOLVED
  * ~~Help tutorial team~~ RESOLVED

## README

* Reviewer: Luis H.
  * "Add a video...? Just kidding."

* Reviewer: Nelll W.
  * Looks outdated, since the highlighted traceback now shows in the Python

* Reviewer: Collin V., Jamie K.
  * Looks good.

**Comment by mjenrungrot** [comment]
Can we close this @nkadonaga ?
